server:
  port: 8080
spring:
    datasource:
        driverClassName: org.postgresql.Driver
        initialization-mode: always
        password: root
        url: jdbc:postgresql://localhost:5432/tripShareApi?useTimezone=true&serverTimezone=UTC
        username: postgres
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL81Dialect
                format_sql: true
        show-sql: true
